version: '3.1'

services:
  db:
    image: library/postgres:14beta2-alpine3.14
    privileged: true
    restart: always
    ports:
    - 5432:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: qwerty
      POSTGRES_DB: library
  adminer:
    image: adminer:4.7.8-standalone
    restart: always
    ports:
      - 8099:8080
    depends_on:
      - db
