version: '3.1'

services:
  db:
    image: library/postgres:14beta2-alpine3.14
    privileged: true
    restart: always
    ports:
    - 5432:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: qwerty
      POSTGRES_DB: db
  adminer:
    image: adminer:4.7.8-standalone
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db
  backend:
    build:
      context: .
    ports:
      - 8070:8070
    command:
      bash -c "
        python3 manage.py migrate &&
        gunicorn library.wsgi -b 0.0.0.0:8070
      "
    depends_on:
      - db
  nginx:
    build: ./nginx
    ports:
      - 8077:80
    depends_on:
      - backend
  frontend:
    build: ./frontend
    ports:
      - 80:80
    depends_on:
      - nginx
